Tokenizing input final
EVelez79/CodeU-ProjectGroup6 pull request #9
Opened 2017-06-09 04:54 UTC by juliachin123

Everything should be working properly now.

2017-06-09 15:18 UTC, evelez7 reviewed
The build will not compile due to missing imports and symbols.

2017-06-09 15:18 UTC, evelez7 commented on src/codeu/chat/client/commandline/Chat.java
> +    final List<String> args = new ArrayList<>();
You deleted the tokens object but tokens is still being used below (on line 73). There will be a complaint at compilation stating that it cannot find symbol `tokens`. 

Also, List has not been imported to this class so there will be a "cannot find symbol error" for List.

2017-06-09 15:18 UTC, evelez7 commented on src/codeu/chat/client/commandline/Chat.java
> +    final Tokenizer tokenizer = new Tokenizer(line);
The Tokenizer class has not been imported so there will be another "cannot find symbol" error.

2017-06-09 15:18 UTC, EVelez79 commented on test/codeu/chat/TestRunner.java
> +             codeu.chat.util.store.StoreTest.class,
When I try running TestRunner, it says the class can not be found or loaded. Not exactly sure what's causing this.

2017-06-09 15:24 UTC, Tuxdude requested changes
I'm sorry but your code still does not compile. Did you try building the code and ensuring the tests pass before sending the pull request? Please please do that, that is the only quick and real way to verify the changes.

Also try running `git status` and it will tell you if you have any local files/changes which have not been committed. This could be another cause why you might see the builds succeeding but others still see a failing build.

```
src/codeu/chat/client/commandline/Panel.java:51: error: cannot find symbol
  public boolean handleCommand(String commandName, List<String> args) {
                                                   ^
  symbol:   class List
  location: class Panel
src/codeu/chat/client/commandline/Chat.java:50: error: cannot find symbol
    final List<String> args = new ArrayList<>();
          ^
  symbol:   class List
  location: class Chat
src/codeu/chat/client/commandline/Chat.java:50: error: cannot find symbol
    final List<String> args = new ArrayList<>();
                                  ^
  symbol:   class ArrayList
  location: class Chat
src/codeu/chat/client/commandline/Chat.java:51: error: cannot find symbol
    final Tokenizer tokenizer = new Tokenizer(line);
          ^
  symbol:   class Tokenizer
  location: class Chat
src/codeu/chat/client/commandline/Chat.java:51: error: cannot find symbol
    final Tokenizer tokenizer = new Tokenizer(line);
                                    ^
  symbol:   class Tokenizer
  location: class Chat
src/codeu/chat/client/commandline/Chat.java:73: error: cannot find symbol
    if (panels.peek().handleCommand(command, tokens)) {
                                             ^
  symbol:   variable tokens
  location: class Chat
6 errors
1 warning
Build FAILED
```

2017-06-09 15:24 UTC, Tuxdude commented on test/codeu/chat/util/TokenizerTest.java
> +		final Tokenizer tokenizer = new Tokenizer("  ");
Could you also add few `\n`, `\r`, `\t` characters in the input string since they are also whitespaces.

2017-06-09 15:24 UTC, Tuxdude commented on test/codeu/chat/util/TokenizerTest.java
> +		final Tokenizer tokenizer = new Tokenizer(null);
The input should be `""` and not `null`.

If you want to test for the null case, please add a separate test if needed. I would not worry about testing null specifically here.

2017-06-09 15:24 UTC, Tuxdude commented on test/codeu/chat/util/TokenizerTest.java
> +		final Tokenizer tokenizer = new Tokenizer("\"hello world how are you");
Could you double check if this is the expected output when you have only one quotation ?

2017-06-10 20:44 UTC, Tuxdude requested changes
For the most part changes look good, except for the 2 failing test cases. Please fix them.

https://travis-ci.org/EVelez79/CodeU-ProjectGroup6/jobs/241463325

```
$ python build.py run codeu.chat.TestRunner
Running: [ java -cp bin:third_party/junit4-4.11.jar:third_party/hamcrest-core-1.3.jar codeu.chat.TestRunner ]
testWithWhiteSpaces(codeu.chat.util.TokenizerTest): expected:<null> but was:<
>
testWithEmptyString(codeu.chat.util.TokenizerTest): expected:<null> but was:<>
false
```

2017-06-10 20:44 UTC, Tuxdude commented on test/codeu/chat/TestRunner.java
> +             codeu.chat.util.store.StoreTest.class,
I think earlier builds were failing and that is a pre-requisite to be able to run the tests.

With recent changes from Julia, I think it runs the tests.

EDIT: This is a reply to Erick's comment itself, dont know why github shows them isolated :|

2017-06-10 20:44 UTC, Tuxdude commented on test/codeu/chat/util/TokenizerTest.java
> +		final Tokenizer tokenizer = new Tokenizer("\n \r \t");
This matches your implementation, but do you really want the whitespace characters as tokens?

If it were me, I would modify Tokenizer to automatically ignore the whitespaces (use `String.trim()` method I suggested last time). It should be fine to do this in a separate pull request as this part is not covered directly by your mini feature.

Also this test is failing, you will still have to fix this.

2017-06-10 20:44 UTC, Tuxdude commented on test/codeu/chat/util/TokenizerTest.java
> +	public void testWithEmptyString() throws IOException {
This test is also failing.

2017-06-10 20:44 UTC, Tuxdude commented on src/codeu/chat/client/commandline/Chat.java
>  import java.util.Scanner;
It should be safe to get rid of this import.

2017-06-10 20:44 UTC, Tuxdude commented on src/codeu/chat/client/commandline/Panel.java
>  import java.util.Scanner;
It should be safe to get rid of this import as well.

2017-06-10 20:44 UTC, Tuxdude commented on test/codeu/chat/TestRunner.java
> +
nit: You can get rid of these extra empty lines.

2017-06-11 19:48 UTC, netcables approved these changes
LGTM. Tests all passed and all of the commands worked properly when I tried to run ClientMain.

2017-06-11 19:53 UTC, Tuxdude commented
LGTM. Please remove the unused Scanner imports in `Chat.java` and `Panel.java` like I suggested earlier.

2017-06-11 19:54 UTC, Tuxdude approved these changes

2017-06-11 22:56 UTC, merged